function init(self)
	-- Add initialization code here
	-- Remove this function if not needed
	msg.post('.', 'acquire_input_focus')
	msg.post('main:/camera#camera', 'set_camera_bounds', {bounds = vmath.vector4(0,0,600,1200)})
	
end


function on_input(self, action_id, action)
	
	if action_id == hash('touch') and action.pressed then

		if gui.pick_node(gui.get_node('main_menu_btn'), action.x, action.y) then

			msg.post('main:/loader#loader', 'load_main_menu')
		end

	end
end

